<a href="https://colab.research.google.com/github/vaibhav0726/All-projects-of-jovac/blob/main/FirstLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])

In [5]:
print(a)

[1 2 3 4]


In [12]:
my_list = [[10,20,30,40],[50,60,70,80]]

In [14]:
a = np.array(my_list)

In [16]:
print(a)  # printing a 
print(type(a))  # class name in numpy
print(a.shape)  # shape of list(m*n)
print(a.dtype)  # data type
print(a.size) # total number of elements
print(a.ndim) # number of dimensions

[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>
(2, 4)
int64
8
2
